name: Deploy Next.js App to Azure Web App

on:
  push:
    branches:
      - main


jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.X'

      - name: Zip the application for deployment
        run: zip -r nextjs-app.zip . -x "*.git*"  "node_modules"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: docswap
          package: ./nextjs-app.zip
          publish-profile: ${{ secrets.AZUREWEBAPPPUBLISHPROFILE }}
