name: Build and Deploy Go App to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22

      - name: Check Go Installation
        run: go version

      - name: Install swag
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
          echo "${{ runner.tool_cache }}/go/bin" >> $GITHUB_PATH

      - name: Generate Swagger docs
        run: swag init

      - name: Tidy Go modules
        run: go mod tidy

      - name: Build
        run: go build -o build/go-app

      - name: Deploy to Azure
        uses: Azure/webapps-deploy@v2
        with:
          app-name: docswapbackend
          package: build/
          publish-profile: ${{ secrets.AZUREWEBAPPPUBLISHPROFILE }}
